In [1]:
import os
import numpy as np
import operator

In [2]:
#获取当前工作目录
os.getcwd()
#更改当前工作目录
os.chdir('C:\\Users\\zhangchunlei\\jupyter notebook\\2.2data')
os.getcwd()

'C:\\Users\\zhangchunlei\\jupyter notebook\\2.2data'

In [3]:
def file2matrix(filename):
    #打开文本文件
    fr = open(filename)
    # 读取文本内容
    arrayoLines = fr.readlines()
    #len()函数读取文本的行数
    numberofLines = len(arrayoLines)
    #创建一个numberofLines行，3列的零矩阵
    returnMat = np.zeros((numberofLines,3))
    #创建类别列表
    classLabelVector = []
    #初始化索引值
    index = 0
    for line in arrayoLines:
        # s.strip()截取掉s中所有回车字符
        line = line.strip()
        #s.split()根据'\t'进行分割，成为元素列表
        listFromLine = line.split('\t')
        #选取前3个元素，将他们放到特征矩阵第index行
        returnMat[index,:] =listFromLine[0:3]
        #将最后一列存储到classLabelVector中，注意：a[-1]表示列表最后一个元素
        classLabelVector.append(int(listFromLine[-1]))
        index += 1
        #返回特征矩阵和类别矩阵
    return returnMat,classLabelVector,index,numberofLines,listFromLine
    

In [4]:
returnMat,classLabelVector,index,numberofLines,listFromLine = file2matrix('datingTestSet2.txt')

In [5]:
print('listFromLine:')
print(listFromLine)
print('------------------')
print('numberofLines:')
print(numberofLines)
print('------------------')
print('index:')
print(index)
print('------------------')
print('returnMat:')
print(returnMat)
print('------------------')
print('classLabelVector:')
print(classLabelVector)

listFromLine:
['43757', '7.882601', '1.332446', '3']
------------------
numberofLines:
1000
------------------
index:
1000
------------------
returnMat:
[[  4.09200000e+04   8.32697600e+00   9.53952000e-01]
 [  1.44880000e+04   7.15346900e+00   1.67390400e+00]
 [  2.60520000e+04   1.44187100e+00   8.05124000e-01]
 ..., 
 [  2.65750000e+04   1.06501020e+01   8.66627000e-01]
 [  4.81110000e+04   9.13452800e+00   7.28045000e-01]
 [  4.37570000e+04   7.88260100e+00   1.33244600e+00]]
------------------
classLabelVector:
[3, 2, 1, 1, 1, 1, 3, 3, 1, 3, 1, 1, 2, 1, 1, 1, 1, 1, 2, 3, 2, 1, 2, 3, 2, 3, 2, 3, 2, 1, 3, 1, 3, 1, 2, 1, 1, 2, 3, 3, 1, 2, 3, 3, 3, 1, 1, 1, 1, 2, 2, 1, 3, 2, 2, 2, 2, 3, 1, 2, 1, 2, 2, 2, 2, 2, 3, 2, 3, 1, 2, 3, 2, 2, 1, 3, 1, 1, 3, 3, 1, 2, 3, 1, 3, 1, 2, 2, 1, 1, 3, 3, 1, 2, 1, 3, 3, 2, 1, 1, 3, 1, 2, 3, 3, 2, 3, 3, 1, 2, 3, 2, 1, 3, 1, 2, 1, 1, 2, 3, 2, 3, 2, 3, 2, 1, 3, 3, 3, 1, 3, 2, 2, 3, 1, 3, 3, 3, 1, 3, 1, 1, 3, 3, 2, 3, 3, 1, 2, 3, 2, 2, 3, 3, 3, 1, 2, 2, 1, 

In [6]:
# 数据归一划处理
def autoNorm(dataSet):
    # 按列寻找最值
    minVals = dataSet.min(0)
    maxVals = dataSet.max(0)
    ranges = maxVals - minVals
    normDataSet = np.zeros(np.shape(dataSet))
    m = dataSet.shape[0]
    # tile(minVals,(m,1))复制
    normDataSet = dataSet - tile(minVals,(m,1))
    normDataSet = normDataSet/tile(ranges,(m,1))
    return normDataSet,ranges,minVals

In [ ]:
normMat,ranges,minVals = autoNorm()